import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { supabase } from "@/integrations/supabase/client"
import { useAuth } from "@/contexts/AuthContext"
import { toast } from "@/hooks/use-toast"

export const useOcorrencias = (filters?: { status?: string; tipo?: string }) => {
  const { user } = useAuth()
  
  return useQuery({
    queryKey: ["ocorrencias", filters],
    queryFn: async () => {
      if (!user) return []
      
      let query = supabase
        .from("ocorrencias")
        .select(`
          *,
          viagens (
            id,
            numero,
            data_inicio,
            status
          ),
          veiculos (
            id,
            placa,
            modelo
          ),
          motoristas (
            id,
            nome,
            cpf
          )
        `)
        .order("created_at", { ascending: false })
      
      if (filters?.status && filters.status !== 'all') {
        query = query.eq("status", filters.status as any)
      }
      
      if (filters?.tipo && filters.tipo !== 'all') {
        query = query.eq("tipo", filters.tipo as any)
      }
      
      const { data, error } = await query
      
      if (error) throw error
      return data || []
    },
    staleTime: 30000,
    enabled: !!user,
  })
}

export const useCreateOcorrencia = () => {
  const queryClient = useQueryClient()
  const { user } = useAuth()
  
  return useMutation({
    mutationFn: async (data: {
      tipo: string
      prioridade: string
      titulo: string
      descricao: string
      localizacao?: string
      viagem_id?: string
      veiculo_id?: string
      motorista_id?: string
      observacoes?: string
      deposito_id?: string
    }) => {
      if (!user) throw new Error("User not authenticated")
      
      const { data: ocorrencia, error } = await supabase
        .from("ocorrencias")
        .insert([{
          tipo: data.tipo as any,
          prioridade: data.prioridade as any,
          titulo: data.titulo,
          descricao: data.descricao,
          localizacao: data.localizacao,
          viagem_id: data.viagem_id,
          veiculo_id: data.veiculo_id,
          motorista_id: data.motorista_id,
          observacoes: data.observacoes,
          deposito_id: data.deposito_id,
          criado_por: user.id,
          numero: '', // Will be auto-generated by trigger
        }])
        .select()
        .single()
      
      if (error) throw error
      return ocorrencia
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ocorrencias"] })
      queryClient.invalidateQueries({ queryKey: ["notifications"] })
      toast({
        title: "Ocorrência criada",
        description: "A ocorrência foi registrada com sucesso.",
      })
    },
    onError: (error) => {
      console.error("Error creating ocorrencia:", error)
      toast({
        title: "Erro",
        description: "Não foi possível criar a ocorrência.",
        variant: "destructive",
      })
    },
  })
}

export const useUpdateOcorrencia = () => {
  const queryClient = useQueryClient()
  
  return useMutation({
    mutationFn: async ({ id, ...data }: { id: string; status?: string; resolucao_aplicada?: string; observacoes?: string }) => {
      const updateData: any = { ...data }
      
      // Se está resolvendo, adicionar data de resolução e usuário
      if (data.status === 'resolvida') {
        updateData.data_resolucao = new Date().toISOString()
        updateData.resolvido_por = (await supabase.auth.getUser()).data.user?.id
        updateData.status = 'resolvida' as any
      } else if (data.status) {
        updateData.status = data.status as any
      }
      
      const { data: ocorrencia, error } = await supabase
        .from("ocorrencias")
        .update(updateData)
        .eq("id", id)
        .select()
        .single()
      
      if (error) throw error
      return ocorrencia
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ocorrencias"] })
      queryClient.invalidateQueries({ queryKey: ["notifications"] })
      toast({
        title: "Ocorrência atualizada",
        description: "As alterações foram salvas com sucesso.",
      })
    },
    onError: (error) => {
      console.error("Error updating ocorrencia:", error)
      toast({
        title: "Erro",
        description: "Não foi possível atualizar a ocorrência.",
        variant: "destructive",
      })
    },
  })
}