// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fejvckhuhflndcjuoppy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlanZja2h1aGZsbmRjanVvcHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTkwMTgsImV4cCI6MjA3MDMzNTAxOH0.8hvIEXgBqhS5Z2QcdaNrr6n672EN-zUcmf3VPxgqEyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});